### ISSUE TITLE
Signal icon not working

### ISSUE THREAD

**Issue by ProjectMoon** [molan-git/harbour-themepack-vaidroid#1]
Signal changed their icon some time ago, and now the one included in the pack doesn't seem to work anymore. Possibly some file path adjustment needed?

**Comment by molan-git** [comment]
Since UI Themer for Sailfish OS got removed, no updates are planned for this icon pack.

**Comment by molan-git** [comment]
Thank you. Since UI Themer for Sailfish OS got removed, no updates are planned for this icon pack.

**Comment by molan-git** [comment]
Thank you. Since UI Themer for Sailfish OS got removed, no updates are planned for this icon pack.
